services:
  frontend:
    image: node:22-alpine3.19
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
    command: sh -c "yarn install && yarn start"

  backend:
    image: python:3.12.4-alpine
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app"
    command: sh -c "pip install -r requirements.txt && python app.py"